import type { Metadata } from "next";
import {  Press_Start_2P, Cascadia_Code } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const pressStar2P = Press_Start_2P ({
  variable: '--font-press',
  weight: ['400']
})

const cascadiaCode = Cascadia_Code({
  variable:'--font-cascadia'
})

export const metadata: Metadata = {
  title: "Histogram App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStar2P.variable} ${cascadiaCode.variable} antialiased`}
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
